"""Benchmark workload: 128 prompts across three output-length bands.

Uniform output lengths would retire every row together, which is the one
workload where continuous batching behaves like static batching.
"""

PROMPTS: list[tuple[str, str]] = [
    ('short', 'what is 2+2?'),
    ('short', 'capital of France?'),
    ('short', 'name a color'),
    ('short', 'what is 10-7?'),
    ('short', 'say hi'),
    ('short', 'name a fruit'),
    ('short', 'what is 5*5?'),
    ('short', 'name an animal'),
    ('short', 'name a country'),
    ('short', 'what is 12/4?'),
    ('short', 'name a metal'),
    ('short', 'what colour is the sky?'),
    ('short', 'name a planet'),
    ('short', 'what is 9+6?'),
    ('short', 'name a programming language'),
    ('short', 'what is 100/25?'),
    ('short', 'what is 7*8?'),
    ('short', 'name a vegetable'),
    ('short', 'capital of Japan?'),
    ('short', 'what is 20-13?'),
    ('short', 'name a bird'),
    ('short', 'what is 6*9?'),
    ('short', 'name a shape'),
    ('short', 'capital of Peru?'),
    ('short', 'what is 45/9?'),
    ('short', 'name a mineral'),
    ('short', 'what is 3^3?'),
    ('short', 'name an ocean'),
    ('short', 'what is 15+27?'),
    ('short', 'name a musical instrument'),
    ('short', 'capital of Kenya?'),
    ('short', 'what is 81/9?'),
    ('short', 'name a tree'),
    ('short', 'what is 11*11?'),
    ('short', 'name a season'),
    ('short', 'capital of Norway?'),
    ('short', 'what is 64-29?'),
    ('short', 'name a gas'),
    ('short', 'what is 2^10?'),
    ('short', 'name a continent'),
    ('short', 'what is 144/12?'),
    ('short', 'name an insect'),
    ('short', 'capital of Chile?'),
    ('medium', 'in two sentences, what is a KV cache?'),
    ('medium', 'name three fruits with one fact about each'),
    ('medium', 'write a haiku about GPUs'),
    ('medium', 'why does water boil at a lower temperature at altitude?'),
    ('medium', 'give me three names for a pet cat'),
    ('medium', 'define latency in one sentence'),
    ('medium', 'what does a GPU do, briefly?'),
    ('medium', 'list four prime numbers and why they qualify'),
    ('medium', 'what is a tensor, in two sentences?'),
    ('medium', 'name three sorting algorithms with their big-O'),
    ('medium', 'what is a race condition? give one example'),
    ('medium', 'what does bf16 mean and why use it?'),
    ('medium', 'name three HTTP status codes and when they apply'),
    ('medium', 'what is a context window?'),
    ('medium', 'in two sentences, what is a cache miss?'),
    ('medium', 'give two uses for a hash table'),
    ('medium', 'what is a deadlock? one sentence'),
    ('medium', 'name three NoSQL databases'),
    ('medium', 'what is idempotency, briefly?'),
    ('medium', 'define throughput versus latency'),
    ('medium', 'what is a semaphore used for?'),
    ('medium', 'name three compression algorithms'),
    ('medium', 'what is DNS, in two sentences?'),
    ('medium', 'explain a binary search in three sentences'),
    ('medium', 'what is a memory leak? one example'),
    ('medium', 'name three container orchestrators'),
    ('medium', 'what is TLS for, briefly?'),
    ('medium', 'define a pure function'),
    ('medium', 'what is backpressure in a queue?'),
    ('medium', 'name three graph traversal algorithms'),
    ('medium', 'what is a monad, in two sentences?'),
    ('medium', 'explain CAP theorem briefly'),
    ('medium', 'what is a write-ahead log?'),
    ('medium', 'name three regression metrics'),
    ('medium', 'what is dropout in a neural net?'),
    ('medium', 'define a REST resource in one sentence'),
    ('medium', 'what is a JIT compiler?'),
    ('medium', 'name three garbage collection strategies'),
    ('medium', 'what does SIMD mean?'),
    ('medium', 'explain a bloom filter in two sentences'),
    ('medium', 'what is a mutex?'),
    ('medium', 'what is sharding?'),
    ('medium', 'what is a foreign key, briefly?'),
    ('long', 'how to make pizza?'),
    ('long', 'explain recursion with a worked example'),
    ('long', 'explain how a transformer language model generates text'),
    ('long', 'describe the rules of chess to a beginner'),
    ('long', 'write a short guide to renting your first apartment'),
    ('long', 'explain how attention works in a transformer'),
    ('long', 'explain continuous batching versus static batching'),
    ('long', 'explain why decoding is memory bandwidth bound'),
    ('long', 'walk through what happens when you type a URL into a browser'),
    ('long', 'explain paged attention and the problem it solves'),
    ('long', 'describe the tradeoffs of quantising a model to int8'),
    ('long', 'explain how gradient descent trains a neural network'),
    ('long', 'write a detailed description of a thunderstorm at sea'),
    ('long', 'describe how a database index speeds up a query'),
    ('long', 'explain the roofline model and how to read one'),
    ('long', 'write a short story about a lighthouse keeper'),
    ('long', 'explain how TCP establishes and tears down a connection'),
    ('long', 'describe how a CPU cache hierarchy works'),
    ('long', 'explain the difference between processes and threads'),
    ('long', 'walk through building a simple HTTP server from sockets'),
    ('long', 'explain how git stores commits internally'),
    ('long', 'describe the lifecycle of a Kubernetes pod'),
    ('long', 'explain public key cryptography to a beginner'),
    ('long', 'write a guide to debugging a slow database query'),
    ('long', 'explain how a compiler turns source into machine code'),
    ('long', 'describe how DNS resolution works end to end'),
    ('long', 'explain consistent hashing and where it is used'),
    ('long', 'write a short story about a train station at midnight'),
    ('long', 'explain how a garbage collector decides what to free'),
    ('long', 'describe the tradeoffs between SQL and NoSQL'),
    ('long', 'explain how a load balancer distributes traffic'),
    ('long', 'write a guide to reading a flame graph'),
    ('long', 'explain how virtual memory and paging work'),
    ('long', 'describe how a B-tree stays balanced'),
    ('long', 'explain how speculative decoding speeds up inference'),
    ('long', 'write a detailed description of a bustling night market'),
    ('long', 'explain how OAuth 2.0 authorization code flow works'),
    ('long', 'describe how a message queue guarantees delivery'),
    ('long', 'explain what makes a distributed system eventually consistent'),
    ('long', 'write a short story about the last bookstore on earth'),
    ('long', 'explain how JPEG compression discards information'),
    ('long', 'describe how a raytracer renders a single frame'),
]
