"""Benchmark workload: 64 prompts, mixed output lengths, interleaved.

The order is baked in, not shuffled at run time. Short prompts grouped at the
front would all retire before a single long one finishes, which flatters the
scheduler.
"""

PROMPTS: list[tuple[str, str]] = [
    ('medium', 'list four prime numbers and why they qualify'),
    ('medium', 'what does a GPU do, briefly?'),
    ('medium', 'write a haiku about GPUs'),
    ('medium', 'what does bf16 mean and why use it?'),
    ('medium', 'what is a context window?'),
    ('long', 'describe how a CPU cache hierarchy works'),
    ('medium', 'name three fruits with one fact about each'),
    ('medium', 'what is idempotency, briefly?'),
    ('short', 'what colour is the sky?'),
    ('medium', 'define latency in one sentence'),
    ('long', 'explain the difference between processes and threads'),
    ('short', 'what is 10-7?'),
    ('short', 'name a fruit'),
    ('short', 'name an animal'),
    ('medium', 'what is a semaphore used for?'),
    ('long', 'explain how a transformer language model generates text'),
    ('short', 'name a planet'),
    ('long', 'explain how TCP establishes and tears down a connection'),
    ('short', 'what is 2+2?'),
    ('long', 'write a detailed description of a thunderstorm at sea'),
    ('short', 'capital of France?'),
    ('long', 'explain recursion with a worked example'),
    ('medium', 'define throughput versus latency'),
    ('short', 'name a programming language'),
    ('short', 'what is 100/25?'),
    ('short', 'name a vegetable'),
    ('long', 'write a short guide to renting your first apartment'),
    ('short', 'name a bird'),
    ('long', 'explain how git stores commits internally'),
    ('short', 'name a metal'),
    ('long', 'walk through building a simple HTTP server from sockets'),
    ('long', 'explain how gradient descent trains a neural network'),
    ('medium', 'in two sentences, what is a cache miss?'),
    ('long', 'walk through what happens when you type a URL into a browser'),
    ('short', 'what is 6*9?'),
    ('short', 'say hi'),
    ('long', 'how to make pizza?'),
    ('long', 'explain paged attention and the problem it solves'),
    ('short', 'what is 12/4?'),
    ('medium', 'what is a deadlock? one sentence'),
    ('medium', 'name three HTTP status codes and when they apply'),
    ('long', 'write a short story about a lighthouse keeper'),
    ('medium', 'name three NoSQL databases'),
    ('short', 'what is 5*5?'),
    ('long', 'describe the rules of chess to a beginner'),
    ('short', 'capital of Japan?'),
    ('short', 'name a country'),
    ('long', 'explain the roofline model and how to read one'),
    ('short', 'what is 9+6?'),
    ('medium', 'give two uses for a hash table'),
    ('medium', 'in two sentences, what is a KV cache?'),
    ('medium', 'what is a tensor, in two sentences?'),
    ('short', 'what is 20-13?'),
    ('long', 'describe the tradeoffs of quantising a model to int8'),
    ('long', 'explain why decoding is memory bandwidth bound'),
    ('medium', 'why does water boil at a lower temperature at altitude?'),
    ('medium', 'name three sorting algorithms with their big-O'),
    ('medium', 'what is a race condition? give one example'),
    ('short', 'what is 7*8?'),
    ('short', 'name a color'),
    ('medium', 'give me three names for a pet cat'),
    ('long', 'describe how a database index speeds up a query'),
    ('long', 'explain how attention works in a transformer'),
    ('long', 'explain continuous batching versus static batching'),
]
